version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
        networks:
            static-network:
                ipv4_address: 172.20.128.3
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            static-network:
                ipv4_address: 172.20.128.2
    phpmyadmin:
        networks:
            static-network:
                ipv4_address: 172.20.128.4
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
        #   ip_range: 172.28.5.0/24

volumes:
  mysql-data: